"""initial migration

Revision ID: e69f7de4202f
Revises: 
Create Date: 2025-09-12 11:00:53.519053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69f7de4202f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_sessions',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('otp',
    sa.Column('otp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=30), nullable=True),
    sa.Column('otp_code', sa.String(length=10), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('otp_id')
    )
    op.create_table('onboarding_questions',
    sa.Column('onboarding_question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('questions', sa.String(length=255), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('onboarding_question_id')
    )
    op.create_table('onboarding_requests',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('questions', sa.String(length=255), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=25), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('meal_requests',
    sa.Column('user_request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meal_date', sa.DateTime(), nullable=True),
    sa.Column('meal_type', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_request_id')
    )
    op.create_table('pantries',
    sa.Column('pantry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meal_type', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pantry_id')
    )
    op.create_table('social_auth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('expiry_token', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('session_token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_token_id')
    )
    op.create_table('generated_meals',
    sa.Column('meal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('meal_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prep_time_mins', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['meal_requests.user_request_id'], ),
    sa.PrimaryKeyConstraint('meal_id')
    )
    op.create_table('pantry_requests',
    sa.Column('pantry_request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pantry_id', sa.Integer(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('meal_type', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pantry_id'], ['pantries.pantry_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pantry_request_id')
    )
    op.create_table('meal_favourites',
    sa.Column('meal_favourite_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['generated_meals.meal_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('meal_favourite_id')
    )
    op.create_table('meal_history',
    sa.Column('meal_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('is_cooked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['generated_meals.meal_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('meal_history_id')
    )
    op.create_table('meal_ingredients',
    sa.Column('ingredient_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['generated_meals.meal_id'], ),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('meal_instructions',
    sa.Column('instruction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('instruction_text', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['generated_meals.meal_id'], ),
    sa.PrimaryKeyConstraint('instruction_id')
    )
    op.create_table('meal_nutrition_info',
    sa.Column('nutrition_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('nutrient_name', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['generated_meals.meal_id'], ),
    sa.PrimaryKeyConstraint('nutrition_id')
    )
    op.create_table('pantry_generated_meals',
    sa.Column('pantry_meal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pantry_request_id', sa.Integer(), nullable=True),
    sa.Column('meal_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prep_time_mins', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pantry_request_id'], ['pantry_requests.pantry_request_id'], ),
    sa.PrimaryKeyConstraint('pantry_meal_id')
    )
    op.create_table('pantry_meal_nutrition_info',
    sa.Column('pantry_instruction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pantry_meal_id', sa.Integer(), nullable=True),
    sa.Column('nutrient_name', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pantry_meal_id'], ['pantry_generated_meals.pantry_meal_id'], ),
    sa.PrimaryKeyConstraint('pantry_instruction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pantry_meal_nutrition_info')
    op.drop_table('pantry_generated_meals')
    op.drop_table('meal_nutrition_info')
    op.drop_table('meal_instructions')
    op.drop_table('meal_ingredients')
    op.drop_table('meal_history')
    op.drop_table('meal_favourites')
    op.drop_table('pantry_requests')
    op.drop_table('generated_meals')
    op.drop_table('user_sessions')
    op.drop_table('social_auth')
    op.drop_table('pantries')
    op.drop_table('meal_requests')
    op.drop_table('users')
    op.drop_table('onboarding_requests')
    op.drop_table('onboarding_questions')
    op.drop_table('otp')
    op.drop_table('onboarding_sessions')
    # ### end Alembic commands ###
